---
name: test (workflow_call)
permissions: {}
on:
  workflow_call:
    secrets:
      TAKUMI_GUARD_BOT_ID:
        required: false
jobs:
  test:
    uses: suzuki-shunsuke/test-workflow/.github/workflows/test.yaml@51ece8dcaabff59820bfb2053c56e3cb281cf7b2 # v0.0.1
    with:
      aqua_version: v2.64.0
    permissions:
      pull-requests: read
      contents: read

  go:
    uses: $/.github/workflows/test.yaml
    with:
      aqua_version: v2.64.0
      go-version-file: go.mod
    permissions:
      pull-requests: write
      contents: read # To checkout private repository
      id-token: write
